% FILE: src/utils/apply_cleanline_to_eeg.m

function EEG = apply_cleanline_to_eeg(EEG, config)
    % APPLY_CLEANLINE_TO_EEG - Apply cleanline using config parameters
    %
    % Wrapper function for pop_cleanline that uses parameters from config
    % structure. This ensures consistent cleanline application across
    % all datasets.
    %
    % Syntax: EEG = apply_cleanline_to_eeg(EEG, config)
    %
    % Inputs:
    %   EEG    - EEG structure
    %   config - Configuration structure with cleanline parameters
    %
    % Outputs:
    %   EEG - EEG structure with line noise removed
    %
    % Example:
    %   config = default_config();
    %   EEG = apply_cleanline_to_eeg(EEG, config);

    EEG = pop_cleanline(EEG, ...
        'bandwidth', config.cleanline.bandwidth, ...
        'chanlist', [1:EEG.nbchan], ...
        'computepower', 1, ...
        'linefreqs', config.cleanline.linefreqs, ...
        'normSpectrum', config.cleanline.normSpectrum, ...
        'p', config.cleanline.p, ...
        'pad', config.cleanline.pad, ...
        'plotfigures', config.cleanline.plotfigures, ...
        'scanforlines', config.cleanline.scanforlines, ...
        'sigtype', config.cleanline.sigtype, ...
        'tau', config.cleanline.tau, ...
        'verb', config.cleanline.verb, ...
        'winsize', config.cleanline.winsize, ...
        'winstep', config.cleanline.winstep);
end